import {
  LayoutDashboard,
  FileEdit,
  FolderTree,
  Tag,
  BellRing,
  FileText,
  Image as ImageIcon,
  Library,
  BookOpen,
  MenuSquare,
  Sliders,
  Users,
  ShieldCheck,
  History,
  Settings,
  Activity,
  Globe,
} from 'lucide-react';
import { NavigationGroup } from './types';

/**
 * Admin Navigation Configuration for School News Platform CMS Shell
 * Modular groups filtered dynamically by module enablement and permissions.
 */
export const adminNavigationGroups: NavigationGroup[] = [
  {
    key: 'overview',
    title: 'TỔNG QUAN',
    items: [
      {
        key: 'admin-dashboard',
        label: 'Bảng điều khiển',
        href: '/admin',
        icon: LayoutDashboard,
      },
    ],
  },
  {
    key: 'content-management',
    title: 'QUẢN TRỊ NỘI DUNG',
    items: [
      {
        key: 'admin-news',
        label: 'Tin tức & Bài viết',
        href: '/admin/news',
        icon: FileEdit,
        moduleKey: 'news',
        requiredPermission: 'news.view',
      },
      {
        key: 'admin-categories',
        label: 'Chuyên mục tin',
        href: '/admin/categories',
        icon: FolderTree,
        moduleKey: 'categories',
        requiredPermission: 'news.create',
      },
      {
        key: 'admin-tags',
        label: 'Thẻ tag tin',
        href: '/admin/tags',
        icon: Tag,
        moduleKey: 'news',
        requiredPermission: 'news.create',
      },
      {
        key: 'admin-announcements',
        label: 'Thông báo điều hành',
        href: '/admin/announcements',
        icon: BellRing,
        moduleKey: 'announcements',
        requiredPermission: ['announcements.view', 'announcements.create'],
      },
      {
        key: 'admin-documents',
        label: 'Văn bản - Tài liệu',
        href: '/admin/documents',
        icon: FileText,
        moduleKey: 'documents',
        requiredPermission: 'documents.view',
      },
      {
        key: 'admin-media',
        label: 'Thư viện hình ảnh',
        href: '/admin/media',
        icon: ImageIcon,
        moduleKey: 'media',
        requiredPermission: 'media.view',
      },
      {
        key: 'admin-albums',
        label: 'Bộ sưu tập Album',
        href: '/admin/albums',
        icon: Library,
        moduleKey: 'media',
        requiredPermission: 'media.view',
      },
      {
        key: 'admin-pages',
        label: 'Trang thông tin tĩnh',
        href: '/admin/pages',
        icon: BookOpen,
        moduleKey: 'pages',
        requiredPermission: 'pages.view',
      },
    ],
  },
  {
    key: 'system-operations',
    title: 'CẤU HÌNH & HỆ THỐNG',
    items: [
      {
        key: 'admin-settings',
        label: 'Cấu hình & Modules',
        href: '/admin/settings',
        icon: Settings,
        moduleKey: 'settings',
        requiredPermission: 'settings.view',
      },
      {
        key: 'admin-menus',
        label: 'Menu & Điều hướng',
        href: '/admin/menus',
        icon: MenuSquare,
        moduleKey: 'menu',
        requiredPermission: ['settings.view', 'settings.edit'],
      },
      {
        key: 'admin-seo',
        label: 'Cấu hình SEO & MXH',
        href: '/admin/seo',
        icon: Globe,
        moduleKey: 'seo',
        requiredPermission: 'settings.view',
      },
      {
        key: 'admin-homepage',
        label: 'Giao diện trang chủ',
        href: '/admin/homepage',
        icon: Sliders,
        moduleKey: 'homepage',
        requiredPermission: 'homepage.view',
      },
      {
        key: 'admin-users',
        label: 'Người dùng & Cán bộ',
        href: '/admin/users',
        icon: Users,
        moduleKey: 'users',
        requiredPermission: 'users.view',
      },
      {
        key: 'admin-roles',
        label: 'Phân quyền (RBAC)',
        href: '/admin/roles',
        icon: ShieldCheck,
        moduleKey: 'roles',
        requiredPermission: 'users.edit',
      },
      {
        key: 'admin-health',
        label: 'Kiểm tra sức khỏe',
        href: '/admin/health',
        icon: Activity,
        moduleKey: 'health',
        requiredPermission: 'health.view',
      },
      {
        key: 'admin-audit',
        label: 'Nhật ký hoạt động',
        href: '/admin/audit',
        icon: History,
        moduleKey: 'audit',
        requiredPermission: 'audit.view',
      },
    ],
  },
];
